Code-for-SAKE/Sakepedia-Nuxt

pages/brands/_id/index.vue
=> 銘柄表示時に酒蔵がなければ、酒蔵は表示しない。

pages/sakes/index.vue
FIX #32
https://github.com/Code-for-SAKE/Sakepedia-Nuxt/pull/29 とのconflictを直す際にtypesのままになってしまっていたものをsearchTypesに改名
=> Fix bug cant search by tags

pages/bydatas/_id/index.vue
=> 醸造データの表示がおかしいので修正

api/routes/bydatas.js, pages/bydatas/_id/update.vue, pages/bydatas/index.vue
=> 製造年月日の更新ができるようにする。

pages/brands/index.vue, pages/breweries/index.vue, pages/bydatas/index.vue, pages/sakes/index.vue
=> enterで検索を開始できるようにする

components/SakeSelect.vue, pages/brands/_id/index.vue, pages/brands/add.vue, pages/breweries/_id/index.vue, pages/bydatas/add.vue, pages/sakes/add.vue
=> 追加時に紐づくデータは初期設定する

.eslintrc.js, package.json, yarn.lock
=> eslintとprettier導入

api/controllers/breweriesController.js, api/routes/breweries.js, components/BreweriesMap.vue, nuxt.config.js, package-lock.json, package.json, pages/index.vue, yarn.lock
=> add brewery maps #64

api/controllers/breweriesController.js, pages/breweries/_id/update.vue, pages/breweries/add.vue
=> 法人番号の入力を明確化

components/BreweriesMap.vue, pages/index.vue
=> 酒蔵マップのデザイン調整

components/BreweriesMap.vue, nuxt.config.js, package.json, plugins/vue2-leaflet-markercluster.js, yarn.lock
=> 都道府県別にクラスタリング、マーカーサイズ調整

components/BreweriesMap.vue
addressに郵便番号を入力されている場合があった。
正規表現を修正。
=> 郵便番号が入っていても都道府県でクラスタリングされるようにする

components/BreweriesMap.vue
=> 酒蔵マップに現在地ボタンを追加

api/controllers/breweriesController.js, api/models/Brewery.js, pages/breweries/_id/index.vue, pages/breweries/_id/update.vue, pages/breweries/add.vue
Fix https://github.com/Code-for-SAKE/Sakepedia-Nuxt/issues/100
=> 酒蔵に見学や日本酒以外の醸造の項目を追加

api/controllers/breweriesController.js
=> 酒蔵にフィールドを追加　変数名修正

api/controllers/breweriesController.js, pages/breweries/_id/update.vue
登録時に全角カタカナをひらがなに変換、検索時にひらがなで検索
=> ひらがな登録、検索対応 #110

api/controllers/commentsController.js, api/controllers/usersController.js, api/routes/users.js, components/CommentList.vue, layouts/default.vue, pages/auth/account.vue, pages/bydatas/_id/update.vue, pages/user/contribute.vue
#5 
自分が最終更新した酒蔵数、銘柄数、日本酒数を表示
自分の投稿を表示
=> 自分の登録数や投稿などを表示するページを作成

api/controllers/analyticsController.js, api/index.js, api/routes/analytics.js, pages/index.vue
=> 分析用のコントローラを作成して、トップページに登録状況を追加

api/controllers/commentsController.js, api/controllers/sakesController.js, api/models/Comment.js, api/models/Sake.js, components/BrandSelect.vue, components/BrewerySelect.vue, components/MariageSelect.vue, components/SakeSelect.vue, components/TagSelect.vue, pages/comments/_id/index.vue, pages/comments/_id/update.vue, pages/comments/add.vue, pages/sakes/_id/index.vue, pages/sakes/_id/update.vue, pages/sakes/add.vue
=> 合うおつまみの入力欄を日本酒情報に追加

api/config.js, api/controllers/usersController.js, api/routes/users.js, nuxt.config.js, package.json, pages/auth/account.vue, yarn.lock
以下の対応
#149 
アカウント画面にJWT取得ボタンを作成。
ヘッダーにつければ有効期限内ならログイン中と同じ処理ができる。
=> JWTで更新系API対応

api/controllers/breweriesController.js
=> カフェの情報を試飲で上書きしてしまっていたので、修正

api/controllers/brandsController.js
=> 別の酒蔵で同じ銘柄名なら登録できるようにする。酒蔵ID+銘柄名でユニークチェックをする。

api/controllers/breweryYearDatasController.js, api/models/Brand.js, api/models/Brewery.js, api/models/BreweryYearData.js, api/models/Comment.js, api/models/Sake.js, api/models/User.js, pages/brands/_id/index.vue, pages/breweries/_id/index.vue, pages/bydatas/_id/index.vue, pages/comments/_id/index.vue, pages/sakes/_id/index.vue
=> 作成日、更新日を保持する

api/controllers/breweriesController.js, pages/breweries/_id/update.vue, pages/breweries/add.vue
=> `住所`から`都道府県`を自動入力

components/BreweryMap.vue, pages/breweries/_id/index.vue
=> 酒蔵ページに地図を追加

pages/comments/index.vue
=> Feature/issue #173

components/BrandSelect.vue, components/BrewerySelect.vue, components/SakeSelect.vue
Issue #163 の対応
これにより、URLパラメタからのプルダウンへの値セットにも対応
=> Feature/issue #163

api/controllers/brandsController.js, api/controllers/breweriesController.js, api/controllers/sakesController.js, pages/brands/_id/update.vue
酒蔵・銘柄・日本酒の必須項目以外はnullで更新可能としました
（ !== undefinedの場合は更新対象としています）
=> issue #162 #165 への対応

pages/brands/add.vue, pages/sakes/add.vue
日本酒、銘柄の追加画面の必須項目に小文字で「＊必須」を付記しました。
=> issue#97 日本酒追加、銘柄追加の必須項目の表示を追加

api/controllers/usersController.js, api/routes/auth.js
user.saveをawaitできていなかったのが問題っぽい
=> 最初のユーザー登録で発生する問題を解消

api/controllers/brandsController.js, api/controllers/sakesController.js, api/models/Brand.js, api/models/Sake.js, pages/brands/_id/index.vue, pages/brands/_id/update.vue, pages/brands/add.vue, pages/sakes/_id/index.vue, pages/sakes/_id/update.vue, pages/sakes/add.vue
Issue#142 銘柄にふりがなを付記しました。日本酒のふりがなにも対応しました。
銘柄、日本酒とも、詳細画面では、ふりがなは入力済みの場合のみ表示します。
=> Issue#142 銘柄にふりがなを付記。日本酒のふりがなにも対応

api/controllers/analyticsController.js, api/controllers/usersController.js
#198 
estimatedDocumentCountの方が正確でない分、速度やメモリに優しいっぽい。
https://stackoverflow.com/questions/53542003/how-accurate-is-mongodbs-estimated-count-query
=> countは非推奨になったので対応

api/controllers/brandsController.js, api/controllers/sakesController.js, utils/japanese.js
=> fix: ふりがななしで銘柄を登録できる
